# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Load dataset
data = pd.read_csv("Mall_Customers.csv")

# Display first few rows
print(data.head())

# Select features for clustering
X = data[['Annual Income (k$)', 'Spending Score (1-100)']]

# -----------------------------
# Elbow Method
# -----------------------------
wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1, 11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

# -----------------------------
# K-Means Clustering
# -----------------------------
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)

data['Cluster'] = kmeans.fit_predict(X)

# Display clustered data
print(data.head())

# -----------------------------
# Visualize Clusters
# -----------------------------
plt.figure(figsize=(10, 7))

plt.scatter(
    X[data['Cluster'] == 0]['Annual Income (k$)'],
    X[data['Cluster'] == 0]['Spending Score (1-100)'],
    s=50,
    label='Cluster 1'
)

plt.scatter(
    X[data['Cluster'] == 1]['Annual Income (k$)'],
    X[data['Cluster'] == 1]['Spending Score (1-100)'],
    s=50,
    label='Cluster 2'
)

plt.scatter(
    X[data['Cluster'] == 2]['Annual Income (k$)'],
    X[data['Cluster'] == 2]['Spending Score (1-100)'],
    s=50,
    label='Cluster 3'
)

plt.scatter(
    X[data['Cluster'] == 3]['Annual Income (k$)'],
    X[data['Cluster'] == 3]['Spending Score (1-100)'],
    s=50,
    label='Cluster 4'
)

plt.scatter(
    X[data['Cluster'] == 4]['Annual Income (k$)'],
    X[data['Cluster'] == 4]['Spending Score (1-100)'],
    s=50,
    label='Cluster 5'
)

# Plot Centroids
plt.scatter(
    kmeans.cluster_centers_[:, 0],
    kmeans.cluster_centers_[:, 1],
    s=300,
    c='black',
    marker='X',
    label='Centroids'
)

plt.title('Customer Segmentation using K-Means')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

# -----------------------------
# Cluster Summary
# -----------------------------
print("\nCluster Summary:")
print(data.groupby('Cluster')[['Annual Income (k$)',
                               'Spending Score (1-100)']].mean())